### Petición para registrar un usuario
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "john",
  "password": "mypassword"
}

### Obtener usuarios
GET http://localhost:3000/api/users/

### Petición para obtener un usuario
GET http://localhost:3000/api/users/1

### Petición para actualizar un usuario
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "username": "john_updated",
  "password": "newpassword"
}

### Petición para eliminar un usuario
DELETE http://localhost:3000/api/users/1

### Petición para iniciar sesión
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "12345"
}

### Petición para crear un evento
POST http://localhost:3000/api/events/
Content-Type: application/json

{
  "title": "Concert",
  "description": "A live concert event.",
  "date": "2024-12-25"
}

### Petición para obtener eventos
GET http://localhost:3000/api/events/

### Petición para actualizar un evento
PUT http://localhost:3000/api/events/1
Content-Type: application/json

{
  "title": "Updated Concert",
  "description": "An updated live concert event.",
  "date": "2024-12-26"
}

### Petición para eliminar un evento
DELETE http://localhost:3000/api/events/1

### Obtener un evento
GET http://localhost:3000/api/events/1

### Create inscripciones
POST http://localhost:3000/api/inscripciones/
Content-Type: application/json

{
  "id_usuario": 1,
  "id_evento": 1
}
